name: RELEASE
on:
  pull_request:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: 🚚
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 🧱
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: ➕
        run: npm i

      - name: 💚
        run: npm run package

      - name: 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
